language: node_js
node_js:
- "7"
branches:
  only:
    - master
script:
- echo "Deploy!!"
install:
- npm install -g firebase-tools
after_success:
- cd functions
- npm install
- firebase deploy --token $FIREBASE_TOKEN
